### ISSUE TITLE
Dados sensíveis - Variáveis de Ambiente 

### ISSUE THREAD

**Issue by giselerosa** [mariioreiis/teste-cypress#1]
@mariioreiis Com relação aos dados sensíveis do repositório recomendaria que desse uma olhada na prática de variáveis de ambiente. Vou deixar uns links de referência pra você :

1. https://github.com/pagarme/cafe-com-testes/blob/main/artigos/cypress-variaveis-de-ambiente.md
2. https://docs.cypress.io/guides/guides/environment-variables

**Comment by mariioreiis** [comment]
Feito, obrigado pelo conteúdo de apoio!
