### ISSUE TITLE
Ignorar arquivos desnecessário 

### ISSUE THREAD

**Issue by giselerosa** [mariioreiis/teste-cypress#3]
Não é uma boa prática subir a node_modules no repositório , dado que o package.json já especifica as dependência e pode ser usado pra baixar as mesmas em todo e qualquer ambiente , seja ele local ou cloud. Recomendo criar um arquivo .gitignore e incluir nele os arquivos que não podem ou devem subir no repositório.

**Comment by mariioreiis** [comment]
Feito!
